version: 2

jobs:
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:7-browsers
              environment:
                  CHROME_BIN: "/usr/bin/google-chrome"
        steps:

            ##
            # SETUP
            ##
            - checkout
            - run:
                name: Install node global dependencies
                command: |
                  sudo npm install -g yarn \
                    bower \
                    ember-cli \

            ##
            # NPM
            ##
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: yarn install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules

            ##
            # BOWER
            ##
            - restore_cache:
                key: dependency-cache-{{ checksum "bower.json" }}
            - run:
                name: Install bower dependencies
                command: bower install
            - save_cache:
                  key: dependency-cache-{{ checksum "bower.json" }}
                  paths:
                      - ./bower_components

            ##
            # TESTS
            ##
            - run:
                name: Run Ember Tests
                command: |
                  JOBS=1 COVERAGE=true ember test

